### ISSUE TITLE
0.1 pre-release for others to play with

### ISSUE THREAD

**Issue by Wotuu** [bjuppa/laravel-blog#4]
Hey,

This issue is possibly on my side but I've no clue why it won't work. I'm interested in integrating your blog package into my website, but ran into the following:

![image](https://user-images.githubusercontent.com/811809/43131472-6865cdca-8f39-11e8-8222-8afffe3212db.png)

It's rather strange it can find your package and then not find it? Is this something to do with that this project is not officially released yet?

**Comment by bjuppa** [comment]
@Wotuu thanks for checking out my laravel-blog package!

Yes, as you suspect, the package doesn't yet have a public release... that may be why it won't install for you.

But composer usually says something like "at any version for your minimum-stability" when that happens, so perhaps something else is wrong.

What happens if you try:

```
composer require bjuppa/laravel-blog:dev-master
```

**Comment by Wotuu** [comment]
Hey man, appreciate the reply. I've managed to include the package now, thanks! I take it that the moment you push more commits to master I will get them as well the moment I update my dependencies? Which may not be what I want when you commit something that's broken, as usually happens on master ;). I'll see if I can integrate the blog soon and look from there, cheers!

**Comment by bjuppa** [comment]
Yes, whenever I tinker with the master-branch you'd get the changes on update... and I'm sure there will be at least some breaking changes before the `1.0` release.

As at least 3 people have now showed their interest, I think I'll do a `0.1` release asap. That way you guys can at least start experimenting without worrying about unpleasant surprises.

I'll update here when there is a release to lock your version to!

**Comment by Wotuu** [comment]
That would be great and very much appreciated! I'm building a website at the moment and I'm kind of on a tight schedule for it so I don't have time to even make some basic blogging functionality. I do want to include the blog for news/release notes though :). No rush, thanks very much for your efforts! I'll update when I integrated it and/or have questions.

**Comment by bjuppa** [comment]
There you go @Wotuu, I've tagged a `0.1` pre-release!

For example, you can now lock version to `^0.1` in `composer.json`!

And, feel free to open new issues as you go!

**Comment by Wotuu** [comment]
Awesome! Thank you very much for the quick release, I think I'll have some
time this weekend to integrate and give you some feedback if I have any.

Have a great weekend!
