### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by alighasemzadeh** [bjuppa/laravel-blog#77]
When I want to install node packages i get:
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: eslint@7.8.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.8.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"6.2.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by bjuppa** [comment]
Hi @alighasemzadeh ! What is it you're trying to achieve with an npm install?

Using my laravel-blog package in your Laravel app doesn't require tinkering with node dependencies, I only use it to build assets during development. I've even removed package.json from the distributed package :) https://github.com/bjuppa/laravel-blog/blob/f6a102d63efb673d412ff59bc2060d5262fbdfb3/.gitattributes#L13

**Comment by alighasemzadeh** [comment]
@bjuppa 
Sorry wrong repo.
