### ISSUE TITLE
Fix compatibility with CommonMark v2

### ISSUE THREAD

**Issue by michelmelo** [bjuppa/laravel-blog#78]
laravel 8.12
php 8
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bjuppa/laravel-blog v1.8.0 requires illuminate/view 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> found illuminate/view[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bjuppa/laravel-blog[v1.8.1, ..., v1.8.2] require league/commonmark ^1.3 -> found league/commonmark[1.3.0, ..., 1.6.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires bjuppa/laravel-blog ^1.8 -> satisfiable by bjuppa/laravel-blog[v1.8.0, v1.8.1, v1.8.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by bjuppa** [comment]
Thanks for the report! I wonder if Laravel has switched to require `league/commonmark` v2 since the last release of this package.

I'll investigate and see if it's possible to quickly release a new version.

**Comment by bjuppa** [comment]
So... from https://github.com/laravel/framework/pull/37954 we have the option to install either version 1.3 or 2 of commonmark.
This package is still on commonmark 1.3

@michelmelo you could try downgrading commonmark to 1.3 if you really want to install it now.

I'll go on to check the commonmark changelog to find out if there is anything holding us back from updating this package too.

**Comment by bjuppa** [comment]
I've added compatibility with both CommonMark 1.x and 2.x and [created a new release](https://github.com/bjuppa/laravel-blog/releases/tag/v1.8.3).

Hopefully this will solve you install conflict @michelmelo
